### ISSUE TITLE
과제수업 코드리뷰

### ISSUE THREAD

**Issue by samgashyeong** [2tle/PracRetroFit#1]
싱글톤 코드에 이상이 있음.
코틀린에서는 object에다가 굳이 if문을 거치면서까지 싱글톤 코드를 쓸 필요는 없습니다. 자세한건 수업 pdf랑 카카오톡으로 보낸 링크를 참고하길 바라겠습니다.

**Comment by 2tle** [comment]
넵 수정했습니다!
